<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="blog.aspx.cs" Inherits="blog" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div id="page">
		<div>
			<div id="body">
				<div id="figure">
					<img src="images/headline-blog.jpg" alt="Image"/>
				</div>
				<div>
					<a href="blog.aspx" class="blog">Blog</a>
					<div id="blog">
						<ul style="width:auto">
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:myDB %>" SelectCommand="SELECT * FROM [blogs]" DeleteCommand="DELETE FROM blogs WHERE Id = @Id" InsertCommand="INSERT INTO blogs(Id, dates, name, reads, link) VALUES (@Id, @dates, @name, @reads, @link)" UpdateCommand="UPDATE blogs
SET dates = @dates, name =@name, reads=@reads, link = @link WHERE Id=@Id">
    <DeleteParameters>
        <asp:Parameter Name="Id" />
    </DeleteParameters>
    <InsertParameters>
        <asp:Parameter Name="Id" />
        <asp:Parameter Name="dates" />
        <asp:Parameter Name="name" />
        <asp:Parameter Name="reads" />
        <asp:Parameter Name="link" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="dates" />
        <asp:Parameter Name="name" />
        <asp:Parameter Name="reads" />
        <asp:Parameter Name="link" />
        <asp:Parameter Name="Id" />
    </UpdateParameters>
                            </asp:SqlDataSource>
        <asp:LinkButton ID="LinkButton1" runat="server" Text="ADD BLOG" Font-Bold="true" ForeColor="Navy" OnClick="LinkButton1_Click" Visible="false"></asp:LinkButton>                      
                 
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" DataSourceID="SqlDataSource1" DataKeyNames="Id" GridLines="Horizontal" RowStyle-BorderColor="Olive" RowStyle-BorderWidth="3" BorderColor="Wheat" AllowPaging="True">
            <Columns>
                <asp:TemplateField SortExpression="name">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                       
                        <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl='<%#String.Format("http://{0}", Eval("link").ToString()) %>' >
           
             <asp:Label ID="Label4" runat="server" Text='<%#Eval("name") %>' Font-Bold="true" Font-Size="Large" ForeColor="Navy"></asp:Label>
                            
            </asp:HyperLink>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField SortExpression="reads">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("reads") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("reads") %>' Font-Size="Medium" Font-Bold="true"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField SortExpression="link">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("link") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        </ItemTemplate>
                </asp:TemplateField>
                 <asp:TemplateField SortExpression="dates">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("dates") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("dates") %>' Font-Size="Medium" Font-Bold="true" ForeColor="Navy"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

            </Columns>
                        
        </asp:GridView>                         
        
                            <asp:DetailsView ID="DetailsView1" runat="server" OnItemCommand="DetailsView1_ItemCommand" 
         OnItemInserted="DetailsView1_ItemInserted" DefaultMode="Insert" Visible="false" OnModeChanging="DetailsView1_ModeChanging"
         AutoGenerateRows="False" DataSourceID="SqlDataSource1" DataKeyNames="Id" EnableViewState="False" GridLines="Horizontal" RowStyle-BorderColor="Tan" RowStyle-BorderWidth="5" OnItemInserting="DetailsView1_ItemInserting">
                                       
                                <Fields>
                                    <asp:TemplateField HeaderText="Title:" SortExpression="name" HeaderStyle-Font-Bold="true" HeaderStyle-Font-Size="Medium">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <InsertItemTemplate>

                                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("name") %>' ></asp:TextBox>
                                             <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ErrorMessage="Field Required" ControlToValidate="TextBox1" Display="Dynamic"></asp:RequiredFieldValidator>
                                        
                                        </InsertItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Add Some Content" SortExpression="reads" HeaderStyle-Font-Bold="true" HeaderStyle-Font-Size="Medium" >
                                        <EditItemTemplate>
                                            <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("reads") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <InsertItemTemplate>
                                            <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("reads") %>'></asp:TextBox>
                             <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ErrorMessage="Field Required" ControlToValidate="TextBox2" Display="Dynamic"></asp:RequiredFieldValidator>
                                        
                                        </InsertItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("reads") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Add Link To Your Blog" SortExpression="link" HeaderStyle-Font-Bold="true" HeaderStyle-Font-Size="Medium">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("link") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <InsertItemTemplate>
                                            <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("link") %>'></asp:TextBox>
                                             <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ErrorMessage="Field Required" ControlToValidate="TextBox3" Display="Dynamic"></asp:RequiredFieldValidator>
                                        
                                        </InsertItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("link") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    
                                    <asp:TemplateField ShowHeader="False">
                                        <InsertItemTemplate>
                                            <asp:LinkButton ID="LinkButton1" runat="server" CausesValidation="True" CommandName="Insert" Text="Insert"></asp:LinkButton>
                                            &nbsp;<asp:LinkButton ID="LinkButton2" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel"></asp:LinkButton>
                                        </InsertItemTemplate>
                                        <EditItemTemplate>
                                           <asp:LinkButton ID="LinkButton1" runat="server" CausesValidation="True" CommandName="Update" Text="Update"></asp:LinkButton>
                                            &nbsp;<asp:LinkButton ID="LinkButton2" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel"></asp:LinkButton>
                                        </EditItemTemplate>
                                        
                                        <ItemTemplate>
                                            </ItemTemplate>
                                    </asp:TemplateField>
    
                                </Fields>




                            </asp:DetailsView> 
                            
                            
                            
                            
                            
                                                
        				</ul>
					</div>
				</div>
			</div>
			</div>
		</div>
	
</asp:Content>

