using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Tips : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        GridView1.DataBind();

        if (Roles.IsUserInRole(User.Identity.Name, "Admin"))
        {
            //to make gridview editable only to Admin

            GridView1.AutoGenerateEditButton = true;
            GridView1.AutoGenerateDeleteButton = true;


        }
        if (Roles.IsUserInRole(User.Identity.Name, "User"))
        {
            //to be able to add new blog, only if its a logged in user
            LinkButton1.Visible = true;

        }
    }

    protected void LinkButton1_Click(object sender, EventArgs e)
    {
        GridView1.Visible = false;
        DetailsView1.Visible = true;

    }
    protected void DetailsView1_ItemInserting(object sender, DetailsViewInsertEventArgs e)
    {
        int num = GridView1.Rows.Count;
        SqlDataSource1.InsertParameters["Id"].DefaultValue = Convert.ToString(num + (int.Parse("1")));
        SqlDataSource1.InsertParameters["dates"].DefaultValue = DateTime.Today.ToShortDateString();


    }

    protected void DetailsView1_ItemInserted(object sender, DetailsViewInsertedEventArgs e)
    {

        DetailsView1.DataBind();
        GridView1.DataBind();
        GridView1.Visible = true;
        DetailsView1.Visible = false;
    }
    protected void DetailsView1_ItemCommand(object sender, DetailsViewCommandEventArgs e)
    {
        if (e.CommandName == "Cancel")
        {
            GridView1.DataBind();
            GridView1.Visible = true;
            DetailsView1.Visible = false;
        }

    }

    protected void DetailsView1_ModeChanging(object sender, DetailsViewModeEventArgs e)
    {
        GridView1.DataBind();
        GridView1.Visible = true;
        DetailsView1.Visible = false;

    }

}